# Generated by Django 5.0 on 2026-09-26 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vaccine_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vaccinename', models.CharField(max_length=500)),
                ('Age', models.BigIntegerField()),
                ('Dose_number', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Side_effect', models.CharField(max_length=500)),
                ('Manufacture', models.CharField(max_length=100)),
                ('Emergency_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=100)),
                ('hospitalplace', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('hospitalstate', models.CharField(max_length=100)),
                ('hospitalpincode', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Upload_photo', models.CharField(max_length=300)),
                ('licensenumber', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fromtime', models.TimeField()),
                ('Date', models.DateField()),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('VACCINATIONINFORMATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccine_information')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('Upload_photo', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('Dob', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Discription', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=1002)),
                ('Type', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Cid', models.CharField(max_length=100)),
                ('SLOT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.slot')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='country_vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination_country', models.CharField(max_length=100)),
                ('Discription', models.CharField(max_length=1000)),
                ('VACCINATIONINFORMATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccine_information')),
            ],
        ),
        migrations.CreateModel(
            name='VaccineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_no', models.CharField(max_length=100)),
                ('HOSPITAL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.hospital')),
                ('VACCINATIONINFORMATION', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.vaccine_information')),
            ],
        ),
    ]
