# Generated by Django 5.0 on 2026-09-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinestock',
            name='stock_no',
            field=models.IntegerField(default=1),
        ),
    ]
